### ISSUE TITLE
Open custom config

### ISSUE THREAD

**Issue by rmpf** [jexuswebserver/JexusManager#100]
Hi, using iis express portable in a 64 bit windows 10 enterprise the application does not allow to open a custom file the only available option is for a jexusserver. Thanks in advance.

**Comment by lextm** [comment]
Have you installed IIS Express on the machine?

**Comment by rmpf** [comment]
Hi, the iis express for windows 10 is running from my pen drive, portable, not installed on the machine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lextm** [comment]
As officially there is no "portable" IIS Express from Microsoft, Jexus Manager has no plan to support that.

**Comment by rmpf** [comment]
I understand your point, but not your answer. I did not ask for that support, I ask for the feature to browse for a custom config file. Do you mean that jexusmanager, that came in a zip file, depend or relay on iis installation to work properly? Do you mean that if I install the iis the problem would disappear and it would get fixed?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lextm** [comment]
If IIS Express is installed to its default location, then the option will be enabled automatically and you can add any custom config file as you wish.

Jexus Manager does rely on IIS/IIS Express installation folder, to locate the schema files as well as other dependencies. It is a management console, so it is not functional if the underly server does not exist.

**Comment by rmpf** [comment]
Understood. I appreciate your follow up to this matters. Thanks for all your efforts.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
