### ISSUE TITLE
Url Rewrite ignores `ignoreCase` value two-ways

### ISSUE THREAD

**Issue by jerone** [jexuswebserver/JexusManager#108]
### Steps to reproduce 1
1. Create new rule.
2. Check "Ignore case" option under Pattern.
3. See no `ignoreCase` attribute in web.config.

### Steps to reproduce 2
1. Add the following code to your web.config:
```
      <rules>
        <rule name="TEST" enabled="true" stopProcessing="true" patternSyntax="ECMAScript">
          <match url="(.*)" negate="false" ignoreCase="true" />
          <action type="Redirect" url="{R:1}" appendQueryString="true" redirectType="Permanent" statusCode="0" logRewrittenUrl="false" subStatusCode="0" statusReason="" statusDescription="" />
          <conditions trackAllCaptures="false" logicalGrouping="MatchAll" />
        </rule>
      </rules>
```
2. Open URL Rewrite module in JexusManager, open this rule and see the option "Ignore case" under Pattern being off.

_Also it's really frustrating that the URL Rewrite module in JexuxManager needs all properties to be set. If I leave out any attribute in above example (`statusCode="0"` for example), the whole rule will be ignored and an error is thrown._

**Comment by lextm** [comment]
You'd better create a new issue and reveal more about "an error is thrown".
