### ISSUE TITLE
Not work properly on x86

### ISSUE THREAD

**Issue by m3mobile-jyj** [jexuswebserver/JexusManager#111]
I worked on Windows 32bit machine.

Global setting find "%windir%\Mircosoft.NET\Framwork64\...\machine.config",
however, not exist path on 32bit machine.

It seems to be coded wrong pointer size check

`IntPtr.Size == 2 ? "Framework" : "Framework64"`

in Microsoft.Web.Administration\Helper.cs file.

**Comment by lextm** [comment]
Fixed in 12.0.82.0.

**Comment by m3mobile-jyj** [comment]
Wow!! very very fast reply.
Thank you.

**Comment by m3mobile-jyj** [comment]
Sadly, does not work properly yet.

It seems to be code running order problem.

`        public static readonly string FileNameMachineConfig = IsRunningOnMono()
            ? "/Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/machine.config"
            : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),
                "Microsoft.NET",
                ProcessIs32Bit ? "Framework" : "Framework64",
                "v4.0.30319",
                "CONFIG",
                "machine.config");

        public static readonly string FileNameWebConfig = IsRunningOnMono()
            ? "/Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/web.config"
            : Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.Windows),
                "Microsoft.NET",
                ProcessIs32Bit ? "Framework" : "Framework64",
                "v4.0.30319",
                "CONFIG",
                "web.config");

        private static bool ProcessIs32Bit = IntPtr.Size == 4;
`

`        private static bool ProcessIs32Bit = IntPtr.Size == 4;

        public static readonly string FileNameMachineConfig = IsRunningOnMono()
            ? "/Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/machine.config"
            : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),
                "Microsoft.NET",
                ProcessIs32Bit ? "Framework" : "Framework64",
                "v4.0.30319",
                "CONFIG",
                "machine.config");

        public static readonly string FileNameWebConfig = IsRunningOnMono()
            ? "/Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/web.config"
            : Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.Windows),
                "Microsoft.NET",
                ProcessIs32Bit ? "Framework" : "Framework64",
                "v4.0.30319",
                "CONFIG",
                "web.config");
`

It works well after changing order ProcessIs32Bit variable to top position.
