### ISSUE TITLE
Installed on Win10-64 with no errors but will not launch.

### ISSUE THREAD

**Issue by RobGMiller** [jexuswebserver/JexusManager#115]
The app version 12.0.92.0 seems to have installed properly but when I try to launch it from the installed shortcut it tries to run but gives up.  There are two associated Event Viewer Windows Application error logs

Application Error as follows: 

Faulting application name: JexusManager.exe, version: 12.0.92.0, time stamp: 0x5cfc3fb9
Faulting module name: KERNELBASE.dll, version: 10.0.17134.799, time stamp: 0x08a3d2a4
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x38bc
Faulting application start time: 0x01d526ad5c4bec2e
Faulting application path: D:\Program Files\Jexus Manager\JexusManager.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b8c4ac2f-134b-44c8-9376-dd88e83581f7
Faulting package full name: 
Faulting package-relative application ID: 

and .NET Runtime

Application: JexusManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Rollbar.NetCore.AppSettingsUtility.LoadAppSettings(Rollbar.RollbarConfig)
   at Rollbar.NetStandard.RollbarConfigUtility.Load(Rollbar.RollbarConfig)
   at Rollbar.RollbarLogger..ctor(Boolean, Rollbar.IRollbarConfig)
   at Rollbar.RollbarFactory.CreateNew(Boolean)
   at Rollbar.RollbarLocator+NestedSingleInstance..cctor()

Exception Info: System.TypeInitializationException
   at JexusManager.Program.SetupRollbar()
   at JexusManager.Program.Main(System.String[])

the reason I am installing this is to try to get IIS Express to run PHP code.
Can you help.

**Comment by lextm** [comment]
The MSI package was wrong.

Please manually upgrade to 12.0.93.0.

**Comment by RobGMiller** [comment]
Thanks. JexusManager works now but PHP still don't work. I added a new post on this forum to get advice on how to get it working. I posted the error message produced by the very handy PHPDiagonostic.
