### ISSUE TITLE
IIS Express wont run PHP

### ISSUE THREAD

**Issue by RobGMiller** [jexuswebserver/JexusManager#116]
IIS Express 10 on Windows 10-64
I try to browse a php site I get the HTTP Error 404.3 - Not Found page

I used Jexus to setup FastCGI in the Global FastCGI Setting configuration feature
   FullPath: D:\Wamp64\bin\php\php7.2.4\php-cgi.exe
I used Jexus to setup the site PHP_via_FastCGI Handler Mappings
   Request Path: *.PHP
   Module: FastCgiModule
   Executable: D:\Wamp64\bin\php\php7.2.4\php-cgi.exe

The site is bound to localhost:9080
It's application Pool is configured to use .Net CLR Version 4.0

PHP Diagnostic returns the following error 

Scan 92 registered handler(s).
* Found an invalid FastCGI handler as {Name: PHP_via_FastCGI, Path: *.PHP, State: Enabled, Module: FastCgiModule, Entry Type: Inhertied } because the path does not exist.
No valid FastCGI handler is registered for this web site.

IIS on this computer is not active and all the sites are stopped. 
I"ve tried it with the World Wide Web Publishing service on and off. 

Any suggestions.

**Comment by lextm** [comment]
Fixed in 12.0.94.0.

**Comment by RobGMiller** [comment]
Thanks for that fix lextm, 
The more detailed PHP diagostic report indicated that the php folder and the system variable was not correct. I changed that and not the PHP diagnotic seems to indicate that all is good. As follows: 


Verify web stack installation versions.
* PHP 7.2 (C:\Program Files (x86)\PHP\v7.2\php-cgi.exe) is supported.
  Visual C++ runtime is detected (expected: 14.11, detected: 14.16.27024.1 built by: vcwrkspc): C:\WINDOWS\SysWOW64\msvcp140.dll.

Windows Path environment variable: C:\Program Files\iis express\PHP\v7.2;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microso;C:\Users\Rob\AppData\Roaming\Composer\vendor\bin;C:\Users\Rob\AppData\Local\Microsoft\WindowsApps;C:\Users\Rob\AppData\Local\Microsoft\WindowsApps;D:\Users\Rob\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Rob\AppData\Local\atom\bin;D:\Wamp64\bin\php\php7.2.4;D:\Program Files\Git\bin;C:\Users\Rob\AppData\Roaming\npm;C:\Program Files (x86)\PHP\v7.2.

[C:\Program Files (x86)\PHP\v7.2]
Found PHP config file C:\Program Files (x86)\PHP\v7.2\php.ini.
PHP loadable extension folder: C:\Program Files (x86)\PHP\v7.2\ext
No extension to verify.
PHP installation has been added to Windows Path environment variable

However, if I run the site from JuxusManager, it tries to copy the index.php file to the local hard drive. If I run it from Visual Studio 2019, it gives the 404.3 page indicating theres is something off about the mimes.  There is a .PHP mime setup for this Site and it's parent. (application/x-httpd-php)

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map. 

Most likely causes:
It is possible that a handler mapping is missing. By default, the static file handler processes all content.
The feature you are trying to use may not be installed.
The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.)
If ASP.NET is not installed.
