### ISSUE TITLE
IIS Express wont run PHP code

### ISSUE THREAD

**Issue by RobGMiller** [jexuswebserver/JexusManager#117]
Thanks for that fix lextm, #116 

Since #116 is close, I thought I might need to post this follow up in a different post. 

The new more detailed PHP diagnostic report indicated that the php folder and the system variable was not correct. I changed that and now the PHP diagnotic seems to indicate that all is good. As follows:

Verify web stack installation versions.

PHP 7.2 (C:\Program Files (x86)\PHP\v7.2\php-cgi.exe) is supported.
Visual C++ runtime is detected (expected: 14.11, detected: 14.16.27024.1 built by: vcwrkspc): C:\WINDOWS\SysWOW64\msvcp140.dll.
Windows Path environment variable: C:\Program Files\iis express\PHP\v7.2;C:\Program Files\Microsoft MPI\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;D:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\QuickTime\QTSystem;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\Microso;C:\Users\Rob\AppData\Roaming\Composer\vendor\bin;C:\Users\Rob\AppData\Local\Microsoft\WindowsApps;C:\Users\Rob\AppData\Local\Microsoft\WindowsApps;D:\Users\Rob\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Rob\AppData\Local\atom\bin;D:\Wamp64\bin\php\php7.2.4;D:\Program Files\Git\bin;C:\Users\Rob\AppData\Roaming\npm;C:\Program Files (x86)\PHP\v7.2.

[C:\Program Files (x86)\PHP\v7.2]
Found PHP config file C:\Program Files (x86)\PHP\v7.2\php.ini.
PHP loadable extension folder: C:\Program Files (x86)\PHP\v7.2\ext
No extension to verify.
PHP installation has been added to Windows Path environment variable

**However, if I run the site from JuxusManager, it tries to copy the index.php file to the local hard drive. If I run it from Visual Studio 2019, it gives the 404.3 page indicating theres is something off about the mimes. There is a .PHP mime setup for this Site and it's parent. (application/x-httpd-php)**

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

Most likely causes:
It is possible that a handler mapping is missing. By default, the static file handler processes all content.
The feature you are trying to use may not be installed.
The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.)
If ASP.NET is not installed.

**Comment by lextm** [comment]
Duplicate to #116 

Whatever happens in Visual Studio is not relevant to Jexus Manager.
