### ISSUE TITLE
Jexus Manager website forgets that it is started (seems to lose connection to iisexpress) after some time

### ISSUE THREAD

**Issue by rwasef1830** [jexuswebserver/JexusManager#122]
Hello,
Another bug I discovered is that if you create a website and then start it. and just stay on the dialog for some time or switch to another window and come back, you will see the UI for Start / Stop / Restart stopped like the site became stopped even though it is still running!

Also, restart website seems to not do anything in this case. It seems like it loses the "connection" with iisexpress after some time.

**Comment by lextm** [comment]
Should have been resolved after tracking PID during the process lifecycle.
