### ISSUE TITLE
URL Rewrite > Exception thrown by target of invocation

### ISSUE THREAD

**Issue by rwasef1830** [jexuswebserver/JexusManager#125]
Hello,
Create any website, then put this web.config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
			<rule name="WordPress: http://localhost:59000" patternSyntax="Wildcard">
				<match url="*"/>
					<conditions>
						<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
						<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true"/>
					</conditions>
				<action type="Rewrite" url="index.php"/>
			</rule></rules>
    </rewrite>
  </system.webServer>
</configuration>
```

Then in Jexus try to open URL Rewrite you will get an error "Exception thrown by target of invocation" and URL rewrite is empty.

Also, all the menu items in the right sidebar in URL rewrite don't work.

**Comment by lextm** [comment]
The rewrite schema provided by Microsoft missed a default value. That's the cause of the exception.

Fixed in 13.0.2.0 release.
