### ISSUE TITLE
asp net core applications sites imported from visual studio solution do not work

### ISSUE THREAD

**Issue by zd-dalibor** [jexuswebserver/JexusManager#128]
Asp net core application imported from visual studio solutions cannot be started in JexusManager because these environment variables are not set: `LAUNCHER_PATH` and `LAUNCHER_ARGS`.

```xml
<!-- applicationhost.config in .vs folder -->
<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600" requestTimeout="23:00:00" />
```

Yes, you could say that I can set these variables manually but what to do when I have more then one  asp net core site in manager with different values for these two variables. Could I set these variables separately for each site in JexusMangaer?

**Comment by lextm** [comment]
.NET Core 3.0 and above start to use a different way to generate this file, which is simpler and more reliable. So, no plan to fix the tool for such legacy format.
