### ISSUE TITLE
Cant enter on any site property

### ISSUE THREAD

**Issue by pipiscrew** [jexuswebserver/JexusManager#132]
hi all,

using JexusManager_x64 v13.0.0.23 on existing IIS configuration (win7x64 / IIS v7.5). 

steps :
-install MSI on 3rd machine
-move the files to target machine
-fire up JexusManager.exe
-success recognize all the sites - ok
-on *sites* can open bindings / basic settings / *reports forms (not tried to change anything for the moment) - ok
-on *sites* view applications / virtual directory / advanced settings / limits  - dont work, just getting nothing when click it - fail
-application pools (start/stop) - ok
-domain properties - ok
-clicking on a *site* getting the properties on right panel

![props](https://user-images.githubusercontent.com/3852762/85929599-f6ac3780-b8be-11ea-96a0-25d9d9314cd8.jpg)

-double click any of them, getting 
![webconfig_error](https://user-images.githubusercontent.com/3852762/85929609-0d528e80-b8bf-11ea-8a88-5c916c90aedf.jpg)

the line *263* on web.config
```
      <compilation debug="true" targetFramework="4.8" />
```

replicated on all 10 sites, the same error.

--

also 
*Browse Website* property on the vertical bar, writes correctly the URL - ok
![2020-06-27_220007](https://user-images.githubusercontent.com/3852762/85930050-f6616b80-b8c1-11ea-90af-ef31fa2eb93d.jpg)

once clicked, drives me to - fail
![2020-06-27_220032](https://user-images.githubusercontent.com/3852762/85930056-00836a00-b8c2-11ea-9dc6-eb399d3409c7.jpg)

**Comment by lextm** [comment]
Assuming this machine has a complete IIS installation, such ASP.NET related items are in the ASPNET_schema.xml file, https://github.com/lextm/iis_schema/blob/master/ASPNET_schema.xml#L137 and Jexus Manager should resolve them without any problem.

You have to review what happens on this specific machine.

BTW, Windows 7 is end of life, so no longer supported by Jexus Manager.
