### ISSUE TITLE
ASP.NET Core Diagnostics throws an exception

### ISSUE THREAD

**Issue by ToraTengu** [jexuswebserver/JexusManager#134]
When i click on the mentioned menu item aUnhandled Exception Dialog shows up instead of the Diagnostics dialog.

Here's the info [Jexus.txt](https://github.com/jexuswebserver/JexusManager/files/5297581/Jexus.txt)

**Comment by lextm** [comment]
Microsoft changed the contents of its manifest files, which was the cause of this problem.

Revised the parsing code accordingly.
