### ISSUE TITLE
How use it with VS 2k19 when debugging in VS

### ISSUE THREAD

**Issue by eliassal** [jexuswebserver/JexusManager#135]
I downloaded yout tool, run it, added a sln solution and updated the bindings as indicated and started the web site. Web site worked and I was able to access it from a remote box. However, when I fire VS, open the project, I can't debug because it can't build the project which I think is because JexusManager is using some files.

When open the file applicationhost.config in .vs directory, I see that bindings were updated correctly but it does not sync with VS.
My problem is that I need to run the project in VS studio in admin mode so it can build and run and debug  and be accessed from remote machines, so how I get aorkaround to not need to run VS in admin mode, thanks

**Comment by lextm** [comment]
Try not to update any bindings created by VS but add new bindings. In that way VS might be friendly enough to register them when debugging on IIS Express.

There is no plan for Jexus Manager to sync any settings for VS/IIS Express, so you have to manually keep the files in sync.

**Comment by eliassal** [comment]
Thanks, I tried, VS does not take into consideration and does not register them, I will give it a 2nd try and let you know

**Comment by lextm** [comment]
Close this as Visual Studio should honor changes to site bindings in `applicationHost.config` files.
