### ISSUE TITLE
Distribute portable version

### ISSUE THREAD

**Issue by pbb72** [jexuswebserver/JexusManager#150]
As it seems to be possible to run Jexus Manager portable (see https://docs.jexusmanager.com/getting-started/install.html#portable-installation), it would be great if the portable version could also be offered through GitHub.

That way:
- One doesn't need access to a machine with admin rights to update the portable version.
- Installers like Scoop could install Jexus Manager.

**Comment by lextm** [comment]
Based on the low download counts, no plan to do any extra work on that part.
