### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by JadynWong** [jexuswebserver/JexusManager#83]
`System.Net.WebException
   在 System.Net.WebClient.UploadDataInternal(System.Uri, System.String, Byte[], System.Net.WebRequest ByRef)
   在 System.Net.WebClient.UploadString(System.Uri, System.String, System.String)
   在 RollbarDotNet.RollbarClient.SendPost[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.__Canon)
   在 RollbarDotNet.RollbarClient.PostItem(RollbarDotNet.Payload)
   在 RollbarDotNet.Rollbar.SendBody(RollbarDotNet.Body, System.Nullable`1<RollbarDotNet.ErrorLevel>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)
   在 RollbarDotNet.Rollbar.Report(System.String, System.Nullable`1<RollbarDotNet.ErrorLevel>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)
   在 JexusManager.Program.SetupRollbar()
   在 JexusManager.Program.Main(System.String[])

`

` <EventData>
  <Data>JexusManager.exe</Data> 
  <Data>2.1.0.54</Data> 
  <Data>59efb1de</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.16299.15</Data> 
  <Data>4736733c</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000013fb8</Data> 
  <Data>29b4</Data> 
  <Data>01d353e7b4ded0ee</Data> 
  <Data>D:\Program Files\JexusManager\JexusManager.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>e5683413-87bf-4112-8a25-8c61191a6a66</Data> 
  <Data /> 
  <Data /> 
  </EventData>`

I try it on 3 pc.Every has the error at Events Viewer.
System windows10 v1709

**Comment by lextm** [comment]
Please run Jexus Manager from command line with `-s` switch, such as
```
JexusManager.exe -s
```

**Comment by JadynWong** [comment]
Thanks.It's ok
