### ISSUE TITLE
NullReferenceException while saving urlrewite setting

### ISSUE THREAD

**Issue by badsaarow** [jexuswebserver/JexusManager#85]
Jexus version : 10.0.206.1
OS : Windows 10

When I tried to save url rewrite setting, jexus manager show error popup as below.
![image](https://user-images.githubusercontent.com/6446223/34427906-8b658efc-ec8a-11e7-895c-1e9450d8e13c.png)

detail exception message is as below.
System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   position: JexusManager.Features.Rewrite.Inbound.InboundRule.Apply()
   position: JexusManager.Features.Rewrite.Inbound.InboundRulePage.ApplyChanges()

**Comment by lextm** [comment]
What is the version number of JexusManager.exe? There is no "10.0.206.1" and I cannot reproduce the issue.

You will have to provide more details, like the steps you did in this dialog before the exception popped up.

**Comment by badsaarow** [comment]
10.0.206.1 is located in Help-> about...  (as below).
![image](https://user-images.githubusercontent.com/6446223/34477215-895814b4-efdb-11e7-9c10-deef3b12b8fb.png)

My step is as below.
![image](https://user-images.githubusercontent.com/6446223/34477281-3e6a83c8-efdc-11e7-81ea-26ce5a1980f4.png)
1. select "Url Rewrite"
2. Select"Add Rule" on URL Rewrite screen
3. add inbound rules
4. fill pattern and "Apply".  Then Exception occurred.

**Comment by lextm** [comment]
You are using a release from 2016. Please upgrade to the latest, and usually such issues have been fixed,

https://github.com/jexuswebserver/JexusManager/releases
