### ISSUE TITLE
It's not working well when using IIS Express host a Web Site on netcore1.0

### ISSUE THREAD

**Issue by 68681395** [jexuswebserver/JexusManager#9]
It's not working well when using IIS Express host a Web Site on netcore1.0

**Comment by lextm** [comment]
![capture](https://cloud.githubusercontent.com/assets/425130/26808536/78e7b2f2-4a2b-11e7-8967-3642a5193361.PNG)

The detailed error message is as attached.

**Comment by lextm** [comment]
For an ASP.NET Core project (in Visual Studio 2017), Visual Studio uses a special way to launch IIS Express,

https://blog.lextudio.com/how-visual-studio-launches-iis-express-to-debug-asp-net-core-apps-d7fd3677e3c3

**Comment by lextm** [comment]
A workaround can be used before I find a permanent fix.

1. Open a command prompt.
1. At this prompt, execute `set LAUNCHER_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe`
1. At this prompt, execute `set LAUNCHER_ARGS=-p "C:\Program Files\dotnet\dotnet.exe" -a "exec \"C:\Users\lextm\documents\visual studio 2017\Projects\WebApplication2\WebApplication2\bin\Debug\netcoreapp1.0\WebApplication2.dll\"" -pidFile "C:\Users\lextm\AppData\Local\Temp\2\tmpFD6D.tmp" -wd "C:\Users\lextm\documents\visual studio 2017\Projects\WebApplication2\WebApplication2"`
1. Launch Jexus Manager from this command prompt.

It is not a convenient way, as you have to change `LAUNCHER_ARGS` for different projects.

**Comment by lextm** [comment]
The new build will analyze the project (currently only `.csproj` is supported), and then attempt to host the site on IIS Express properly by using Visual Studio 2017 bits. Thus, VS2017 (15.2 and above) is required.
