### ISSUE TITLE
Jexus Manager does not run

### ISSUE THREAD

**Issue by hmahdavi921** [jexuswebserver/JexusManager#94]
I download zip file and extract it then double click on the JexusManager.exe  but does not run.
What is problem?

**Comment by lextm** [comment]
In Windows Explorer, right click on JexusManager.exe and open its properties. Unblock it as it was downloaded from the internet.

**Comment by hmahdavi921** [comment]
In properties windows does not exist Unblock option. I check all tabs

**Comment by lextm** [comment]
Can you check Windows event log to see if any more information (errors related to Jexus Manager.exe) can be found? Usually if a program crashes, there should be at least an entry in Application category.
