### ISSUE TITLE
Will it have a Linux version?

### ISSUE THREAD

**Issue by JaneConan** [jexuswebserver/JexusManager#95]

**Comment by lextm** [comment]
You can run Jexus Manager on Linux via Mono, but many exceptions are expected, as the current goal of this project is to merely support Windows/IIS/IIS Express.

Note that there is neither IIS nor IIS Express on Linux, so running Jexus Manager on Linux is meaningless.

**Comment by JaneConan** [comment]
I know, but with more and more dotnetcore projects, many of the same requirements for IIS mounted virtual directories and integrated management increase, don't you consider adding cross-platform support to this

**Comment by lextm** [comment]
Remote managing IIS from a Linux machine is not the mission of this project.

It would be Microsoft who should develop something, and currently IIS REST API is already there,

https://docs.microsoft.com/en-us/iis-administration/

**Comment by JaneConan** [comment]
Thx!
