### ISSUE TITLE
Missing support for wildcard SSL Certificates, when using SNI

### ISSUE THREAD

**Issue by jotabe-net** [jexuswebserver/JexusManager#96]
When trying to set a wildcard certificate for a domain, you get an error like this:

The binding "*:443:my.domain.name" is invalid: SNI mode requires host name matches common name of the certificate.

I think that simple change in BindignUtility would correctly handle this:

    if (binding.GetIsSni())
    {
        var certName = certificate2.GetNameInfo(X509NameType.DnsName, false) ?? "";
    
        // Handle wildcard
        if (certName.StartsWith("*"))
        {
            // Wildcard certificate
            var domain = certName.TrimStart('*');
            if (!binding.Host.EndsWith(domain))
            {
                return "SNI mode requires host name matches wildcard domain name of the certificate";
            }
        }
        else
        {
            if (certName != binding.Host)
            {
                return "SNI mode requires host name matches common name of the certificate";
            }
        }

**Comment by lextm** [comment]
You might send a pull request. Meanwhile, `LikeOperator.LikeString` ([link(https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.compilerservices.likeoperator.likestring?view=netframework-4.7.2#Microsoft_VisualBasic_CompilerServices_LikeOperator_LikeString_System_String_System_String_Microsoft_VisualBasic_CompareMethod_)) should be better an option to check wildcard matching

**Comment by lextm** [comment]
Should be fixed in f22c3733838d1d8fe783086eec89748e28de7e9c now along with SAN support.
